// Admin Pages JavaScript

let pages = [];

// Initialize
document.addEventListener('DOMContentLoaded', () => {
  loadPages();
  setupEventListeners();
});

// Setup Event Listeners
function setupEventListeners() {
  const pageForm = document.getElementById('pageForm');
  if (pageForm) {
    pageForm.addEventListener('submit', savePage);
  }
  
  const pageTitle = document.getElementById('pageTitle');
  if (pageTitle) {
    pageTitle.addEventListener('input', generateSlug);
  }
  
  const searchInput = document.getElementById('searchInput');
  if (searchInput) {
    searchInput.addEventListener('input', filterPages);
  }
}

// Load Pages
function loadPages() {
  pages = JSON.parse(localStorage.getItem('pages') || '[]');
  
  // Create sample pages if empty
  if (pages.length === 0) {
    pages = [
      {
        id: 'PAGE' + Date.now(),
        title: 'Về chúng tôi',
        slug: 've-chung-toi',
        content: '<h2>Về KAITO KID</h2><p>KAITO KID là thương hiệu thời trang trẻ trung, năng động...</p>',
        status: 'published',
        order: 1,
        createdAt: new Date().toISOString()
      },
      {
        id: 'PAGE' + Date.now() + 1,
        title: 'Chính sách bảo mật',
        slug: 'chinh-sach-bao-mat',
        content: '<h2>Chính sách bảo mật</h2><p>Chúng tôi cam kết bảo vệ thông tin cá nhân của khách hàng...</p>',
        status: 'published',
        order: 2,
        createdAt: new Date().toISOString()
      }
    ];
    localStorage.setItem('pages', JSON.stringify(pages));
  }
  
  displayPages();
}

// Display Pages
function displayPages() {
  const tbody = document.getElementById('pagesTableBody');
  if (!tbody) return;
  
  if (pages.length === 0) {
    tbody.innerHTML = `
      <tr>
        <td colspan="6" class="empty-message">
          <i class="fa fa-file"></i> Chưa có trang nào. Nhấn "Thêm trang" để tạo mới.
        </td>
      </tr>
    `;
    return;
  }
  
  tbody.innerHTML = pages
    .sort((a, b) => a.order - b.order)
    .map(page => `
      <tr>
        <td><strong>#${page.id.substring(0, 8)}</strong></td>
        <td>
          <div class="page-item-title">${page.title}</div>
          <div class="page-item-url">/${page.slug}.html</div>
        </td>
        <td>
          <code style="font-size:12px;color:#666;">/${page.slug}.html</code>
        </td>
        <td>
          <span class="page-status-badge ${page.status}">
            <i class="fa fa-${getStatusIcon(page.status)}"></i>
            ${getStatusText(page.status)}
          </span>
        </td>
        <td>${formatDate(page.createdAt)}</td>
        <td>
          <div class="page-actions">
            <button class="btn-page btn-view-page" onclick="viewPage('${page.slug}')" title="Xem trang">
              <i class="fa fa-eye"></i>
            </button>
            <button class="btn-page btn-edit-page" onclick="editPage('${page.id}')" title="Sửa">
              <i class="fa fa-edit"></i>
            </button>
            <button class="btn-page btn-delete-page" onclick="deletePage('${page.id}')" title="Xóa">
              <i class="fa fa-trash"></i>
            </button>
          </div>
        </td>
      </tr>
    `).join('');
}

// Get Status Icon
function getStatusIcon(status) {
  const icons = {
    'published': 'check-circle',
    'draft': 'edit',
    'private': 'lock'
  };
  return icons[status] || 'question-circle';
}

// Get Status Text
function getStatusText(status) {
  const texts = {
    'published': 'Đã xuất bản',
    'draft': 'Bản nháp',
    'private': 'Riêng tư'
  };
  return texts[status] || status;
}

// Generate Slug
function generateSlug() {
  const title = document.getElementById('pageTitle').value;
  const slugInput = document.getElementById('pageSlug');
  
  if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
    const slug = title
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim();
    slugInput.value = slug;
    slugInput.dataset.autoGenerated = 'true';
  }
}

// Filter Pages
function filterPages() {
  const searchTerm = document.getElementById('searchInput').value.toLowerCase();
  const filtered = pages.filter(page => 
    page.title.toLowerCase().includes(searchTerm) ||
    page.slug.toLowerCase().includes(searchTerm)
  );
  
  // Update display with filtered results
  const tbody = document.getElementById('pagesTableBody');
  if (filtered.length === 0) {
    tbody.innerHTML = `
      <tr>
        <td colspan="6" class="empty-message">
          Không tìm thấy trang nào phù hợp.
        </td>
      </tr>
    `;
    return;
  }
  
  tbody.innerHTML = filtered
    .sort((a, b) => a.order - b.order)
    .map(page => `
      <tr>
        <td><strong>#${page.id.substring(0, 8)}</strong></td>
        <td>
          <div class="page-item-title">${page.title}</div>
          <div class="page-item-url">/${page.slug}.html</div>
        </td>
        <td>
          <code style="font-size:12px;color:#666;">/${page.slug}.html</code>
        </td>
        <td>
          <span class="page-status-badge ${page.status}">
            <i class="fa fa-${getStatusIcon(page.status)}"></i>
            ${getStatusText(page.status)}
          </span>
        </td>
        <td>${formatDate(page.createdAt)}</td>
        <td>
          <div class="page-actions">
            <button class="btn-page btn-view-page" onclick="viewPage('${page.slug}')" title="Xem trang">
              <i class="fa fa-eye"></i>
            </button>
            <button class="btn-page btn-edit-page" onclick="editPage('${page.id}')" title="Sửa">
              <i class="fa fa-edit"></i>
            </button>
            <button class="btn-page btn-delete-page" onclick="deletePage('${page.id}')" title="Xóa">
              <i class="fa fa-trash"></i>
            </button>
          </div>
        </td>
      </tr>
    `).join('');
}

// Open Page Modal
function openPageModal(pageId = null) {
  const modal = document.getElementById('pageModal');
  const form = document.getElementById('pageForm');
  const modalTitle = document.getElementById('modalTitle');
  
  if (pageId) {
    const page = pages.find(p => p.id === pageId);
    if (page) {
      modalTitle.textContent = 'Sửa trang';
      document.getElementById('pageId').value = page.id;
      document.getElementById('pageTitle').value = page.title;
      document.getElementById('pageSlug').value = page.slug;
      document.getElementById('pageSlug').dataset.autoGenerated = 'false';
      document.getElementById('pageContent').value = page.content;
      document.getElementById('pageStatus').value = page.status;
      document.getElementById('pageOrder').value = page.order || 1;
    }
  } else {
    modalTitle.textContent = 'Thêm trang mới';
    form.reset();
    document.getElementById('pageId').value = '';
    document.getElementById('pageSlug').dataset.autoGenerated = 'true';
  }
  
  modal.style.display = 'flex';
}

// Close Page Modal
function closePageModal() {
  const modal = document.getElementById('pageModal');
  modal.style.display = 'none';
  document.getElementById('pageForm').reset();
}

// Save Page
function savePage(e) {
  e.preventDefault();
  
  const pageId = document.getElementById('pageId').value;
  const slug = document.getElementById('pageSlug').value;
  
  // Validate slug
  if (!/^[a-z0-9-]+$/.test(slug)) {
    alert('URL chỉ được chứa chữ thường, số và dấu gạch ngang!');
    return;
  }
  
  // Check duplicate slug
  const existingPage = pages.find(p => p.slug === slug && p.id !== pageId);
  if (existingPage) {
    alert('URL này đã được sử dụng bởi trang khác!');
    return;
  }
  
  const page = {
    id: pageId || 'PAGE' + Date.now(),
    title: document.getElementById('pageTitle').value,
    slug: slug,
    content: document.getElementById('pageContent').value,
    status: document.getElementById('pageStatus').value,
    order: parseInt(document.getElementById('pageOrder').value) || 1,
    createdAt: pageId ? pages.find(p => p.id === pageId)?.createdAt || new Date().toISOString() : new Date().toISOString()
  };
  
  if (pageId) {
    const index = pages.findIndex(p => p.id === pageId);
    if (index !== -1) {
      pages[index] = page;
    }
  } else {
    pages.push(page);
  }
  
  localStorage.setItem('pages', JSON.stringify(pages));
  displayPages();
  closePageModal();
  showNotification(pageId ? 'Đã cập nhật trang!' : 'Đã thêm trang mới!', 'success');
}

// Edit Page
function editPage(pageId) {
  openPageModal(pageId);
}

// Delete Page
function deletePage(pageId) {
  if (!confirm('Bạn có chắc muốn xóa trang này?')) return;
  
  pages = pages.filter(p => p.id !== pageId);
  localStorage.setItem('pages', JSON.stringify(pages));
  displayPages();
  showNotification('Đã xóa trang!', 'success');
}

// View Page
function viewPage(slug) {
  window.open(`../${slug}.html`, '_blank');
}

// Format Date
function formatDate(dateString) {
  if (!dateString) return 'N/A';
  const date = new Date(dateString);
  return date.toLocaleDateString('vi-VN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  });
}

// Show Notification
function showNotification(message, type = 'success') {
  alert(message);
}

// Close modal when clicking outside
window.onclick = function(event) {
  const modal = document.getElementById('pageModal');
  if (event.target === modal) {
    closePageModal();
  }
}

