@startuml VOPC_SanPham

class QLSanPhamView
class QLSanPhamController

class SanPham {
    -MaSP : int
    -TenSP : string
    -MaLoai : string
    -Menu : string
    -GiaBan : int
    -GiaGoc : int
    -SoLuongTon : int
    -TrangThai : string
    -HinhAnh : string
    -MoTa : string
    -SKU : string
    -isNew : boolean
    -isSale : boolean
    -isBestSeller : boolean
    -Rating : float
    -SoLuongBan : int
}

class LoaiSP {
    -MaLoai : string
    -TenLoai : string
    -Menu : string
    -MoTa : string
}

class Menu {
    -MaMenu : string
    -TenMenu : string
}

QLSanPhamView --> QLSanPhamController
QLSanPhamController --> SanPham
QLSanPhamController --> LoaiSP
QLSanPhamController --> Menu
SanPham "0..*" -- "1" LoaiSP
LoaiSP "0..*" -- "1" Menu

@enduml
