@startuml VOPC_KhachHang

class QLKhachHangView
class QLKhachHangController

class KhachHang {
    -MaKH : int
    -TenKH : string
    -Email : string
    -SDT : string
    -MaHang : string
    -SoDonHang : int
    -TongChiTieu : int
    -NgayThamGia : datetime
    -TrangThai : string
}

class HangKH {
    -MaHang : string
    -TenHang : string
}

class TaiKhoan {
    -MaTK : int
    -MaKH : int
    -Email : string
    -MatKhau : string
    -NgayTao : datetime
}

class DonHang {
    -MaDH : string
    -MaKH : int
    -TongTien : int
    -NgayDat : datetime
}

QLKhachHangView --> QLKhachHangController
QLKhachHangController --> KhachHang
QLKhachHangController --> HangKH
QLKhachHangController --> TaiKhoan
QLKhachHangController --> DonHang
KhachHang "0..*" -- "1" HangKH
TaiKhoan "1" -- "1" KhachHang
DonHang "0..*" -- "1" KhachHang

@enduml
