@startuml VOPC_TonKho

class QLTonKhoView
class QLTonKhoController

class TonKho {
    -MaSP : int
    -TenSP : string
    -SKU : string
    -MaDanhMuc : string
    -SoLuongTon : int
    -SoLuongBan : int
    -HinhAnh : string
}

class BienThe {
    -MaBT : string
    -MaSP : int
    -Size : string
    -MauSac : string
    -SoLuong : int
}

class LichSuKho {
    -MaLS : string
    -MaSP : int
    -TenSP : string
    -LoaiDieuChinh : string
    -SoLuong : int
    -TonCu : int
    -TonMoi : int
    -GhiChu : string
    -NgayNhap : datetime
}

class SanPham {
    -MaSP : int
    -TenSP : string
    -SoLuongTon : int
}

QLTonKhoView --> QLTonKhoController
QLTonKhoController --> TonKho
QLTonKhoController --> BienThe
QLTonKhoController --> LichSuKho
QLTonKhoController --> SanPham
BienThe "0..*" -- "1" TonKho
LichSuKho "0..*" -- "1" TonKho
TonKho "1" -- "1" SanPham

@enduml
